### PR TITLE
Fixing the funtion's name completely

### PR DESCRIPTION
**Pull request by micaelomota**
Sorry, I forgot to edit some places that the function's name appeared, then one error had gone.
But now I corrected them completely.

### CODE REVIEW

**Comment by nitriques** [comment]
Ah I've missed that ! I've fixed it manually since your changes introduces more changes than needed.
See 36006fa

**Comment by nitriques** [comment]
2.2.0 is out!

**Comment by micaelomota** [comment]
Oh, okay. Thanks for adding my contribution to the project.

**Comment by nitriques** [comment]
Well, thanks for contributing!

**Pull request closed without merging**
