### PR TITLE
Update jquery.quicksearch.js

### LINKED ISSUE #32: Uncaught TypeError: window.clearTimeout is not a function
gnome-shell-imgur-jlqlny

### LINKED ISSUE #34: package.json
package.json support only [single author](https://docs.npmjs.com/files/package.json#people-fields-author-contributors). Other authors must be in contributors section
This breaks the ```grunt build``` task, as it use this in banner configuration. After installing this as NPM module it removes the author configuration from package.json as invalid and build process is failing with a error message:
```
Warning: An error occurred while processing a template (Cannot read property 'name' of undefined). Use --force to continue.
```
https://docs.npmjs.com/files/package.json#people-fields-author-contributors

### PR DESCRIPTION
**Pull request by FDiskas**
window and document are global.
closes #32
closes #34

### CODE REVIEW

**Comment by nitriques** [comment]
Thanks! But I can't merge this.

First, can you setup your text editor to NOT trim whitespace ? Also, please to commit build file, As I need to do it anyhow. Finally, can you push against `dev` instead of `master` ? Thanks.

**Comment by nitriques** [comment]
Also, please keep the window and document variables, as they can be something else ...

**Comment by FDiskas** [comment]
Ok

**Comment by nitriques** [comment]
This is a way to big PR. Sorry I can't review this. Try to split features across multiple PRs. Thanks.

**Comment by FDiskas** [comment]
Just ignore generated files.

**Comment by patrocle** [comment]
Quick fork&fix :
Add "jquery.quicksearch":"https://github.com/patrocle/quicksearch/tarball/master" to package.json 
I Hope future version will be fix because you close this one.

**Comment by nitriques** [comment]
@patrocle You are running webpack too ?

**Pull request closed without merging**
