### PR TITLE
Fixing the function's name completely.

### PR DESCRIPTION
**Pull request by micaelomota**
I forgot of to edit some places that the function's name appeared, then one error had gone along.
But now, I corrected completely.
:]

### CODE REVIEW

**Comment by nitriques** [comment]
Why did you close ?

**Comment by nitriques** [comment]
Ha, please update the dev branch before sending the PR !

**Comment by micaelomota** [comment]
Sorry, I closed because the PR was big and had conflicts. I did it in the branch 'aNewFunction' .
I hope I have not bothered.

**Comment by nitriques** [comment]
No worries, I just wanted to make sure it was not a mistake.

**Pull request closed without merging**
