### PR TITLE
patch-2

### PR DESCRIPTION
**Pull request by FDiskas**

### CODE REVIEW

**Comment by FDiskas** [comment]
do not forget to publish the new version to npm to

**Comment by nitriques** [comment]
This is a way to big PR. Sorry I can't review this.

**Comment by FDiskas** [comment]
what?
the only one file is big - dist/jquery.quicksearch.js
and this file is generated. you just missed some other fixes, like auto build after npm install and so on.
Ok keep work by your self.

**Comment by nitriques** [comment]
> you just missed some other fixes,

Please submit each fix as separated PR, so we can discuss them.

> Missed editorconfig - needed for contributors.

I do not use it, nor do I need it. A good editor can pick up defaults by itself. Also you are imposing your views, not respecting the original code.

> Ok keep work by your self.

Hum can you be more constructive instead of being frustrated ?

**Comment by FDiskas** [comment]
Jumped to other plugin - thanks for help

**Pull request closed without merging**
