### PR TITLE
Improving grunt task loader and fix requirejs compatilibity

### PR DESCRIPTION
**Pull request by RGkevin**
When you are using require.js and try to use this plugin it can´t be loaded properly because of the way it uses jQuery. I just improve the way you load the Grunt tasks and fix this compatilibity problems.

### CODE REVIEW

**Comment by RGkevin** [comment]
Please update bower version because I need this fix in my project, Thanks!

**Comment by nitriques** [comment]
Ok that's cool, but

1. Please separate that PR into multiple, smaller ones...
2. Why are you dropping matchdep ?
3. Please, do not change whitespaces...

:smile:

**Comment by nitriques** [comment]
Oh do not mind, I'll do it manually since it's 3 lines...
https://github.com/DeuxHuitHuit/quicksearch/pull/15/files?w=0

**Comment by RGkevin** [comment]
I dropped matchdep because I got node version problems

**Comment by nitriques** [comment]
> node version problems

which node are you running ? I assume 0.10, 0.12 or io.js ?

**Comment by RGkevin** [comment]
it is v0.10.33. Maybe it wasn't problem with node version, but when I try $ grunt dev it triggers and error that I couldn't find the task, same for all the tast.

**Comment by nitriques** [comment]
>  error that I couldn't find the task, same for all the tast.

I'll dig into that. I must say that I do not find your changes stupid: they are great! But since I maintain a lot of project I would prefer to keep things as is, since it is easier for me. That's all.

I'll release a new version tomorrow morning.

**Comment by nitriques** [comment]
And thanks!

**Comment by RGkevin** [comment]
it's ok. Thanks.

**Comment by nitriques** [comment]
@RGkevin Would you mind testing the latest `dev` branch ? Everything should be fixed. Thanks again.

**Comment by nitriques** [comment]
@RGkevin any updates ? Still waiting for your feedback before pushing to master :+1:

**Comment by nitriques** [comment]
Closing since no feedback.

**Pull request closed without merging**
